<a href="https://colab.research.google.com/github/adnanz98/colab-programming/blob/main/gmhDataset_with_panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import warnings; warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path= "/content/drive/MyDrive/datasets/Global_Mental_Health_Dataset_2025.csv"

In [ ]:
df= pd.read_csv(file_path)
print("loaded: ", df.shape)

loaded:  (2500, 15)

In [ ]:
# Quality checks — run these every time
df.isnull().sum()                            # missing per column

Patient_ID                 0
Age                        0
Gender                     0
Country                    0
Depression_Score           0
Anxiety_Score              0
Stress_Level               0
Sleep_Hours                0
Physical_Activity        477
Chronic_Illness            0
Mental_Health_History      0
Treatment                608
Days_of_Treatment          0
Outcome                    0
Work_Status                0
dtype: int64

In [ ]:
df.head()

,Patient_ID,Age,Gender,Country,Depression_Score,Anxiety_Score,Stress_Level,Sleep_Hours,Physical_Activity,Chronic_Illness,Mental_Health_History,Treatment,Days_of_Treatment,Outcome,Work_Status
0,MH0001,56,Male,Germany,4,10,High,8.2,Moderate,No,No,Therapy,171,Excellent,Unemployed
1,MH0002,69,Male,South Africa,22,4,Severe,6.2,Low,No,Yes,NaN,69,Fair,Employed
2,MH0003,46,Male,South Africa,4,2,Low,10.4,NaN,Yes,Yes,Medication,70,Good,Employed
3,MH0004,32,Female,Australia,19,16,Low,10.0,Moderate,No,Yes,Both,254,Excellent,Employed
4,MH0005,60,Female,United States,14,1,Severe,7.9,Low,Yes,No,Therapy,130,Fair,Employed

In [ ]:
df['Outcome'].value_counts(normalize=True)   # class balance

Outcome
Good         0.3508
Fair         0.3084
Poor         0.1976
Excellent    0.1432
Name: proportion, dtype: float64